### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jesse996** [tinovyatkin/nest-puppeteer#396]
[Nest] 8052   - 2021/04/05下午5:40:29   [ExceptionHandler] Nest can't resolve dependencies of the DouyuService (?). Please make sure that the argument DefaultPuppeteerPage at index [0] is available in the AppModule context.

Potential solutions:
- If DefaultPuppeteerPage is a provider, is it part of the current AppModule?
- If DefaultPuppeteerPage is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing DefaultPuppeteerPage */ ]
  })
 +1ms
Error: Nest can't resolve dependencies of the DouyuService (?). Please make sure that the argument DefaultPuppeteerPage at index [0] is available in the AppModule context.

**Comment by tinovyatkin** [comment]
Do you have PuppeteerModule.forRoot somewhere?

**Comment by jesse996** [comment]
> Do you have PuppeteerModule.forRoot somewhere?

I try ` PuppeteerModule.forRoot ` and `PuppeteerModule.forFeature()` ,same with README.md
